### PR TITLE
Added the Hyperkin X91.

### PR DESCRIPTION
**Pull request by ewtoombs**
It's an xbox one controller. It's just a simple modification of the id tables.

### CODE REVIEW

**Comment by paroj** [comment]
this should not be needed, see https://github.com/paroj/xpad/issues/122#issuecomment-447576415

**Comment by WillSams** [comment]
Eric, I have no problem getting this to work on Linux desktop but having an issue on the RetroPie.  Any ideas on what could be causing the issue?

**Comment by ewtoombs** [comment]
> this should not be needed, see [#122 (comment)](https://github.com/paroj/xpad/issues/122#issuecomment-447576415)

Shouldn't, but it does. Either accept this, or fix the other problem that keeps xpad from finding this xbox gamepad.

**Comment by cgutman** [comment]
This PR adds a new vendor ID entry, so it is actually needed.

**Comment by paroj** [comment]
actually the vendor ID was already there:
https://github.com/paroj/xpad/blob/master/xpad.c#L429

**Comment by etoombs-encircle** [comment]
I don't know why I had to add my controller to this list. I just know that I did. Without at least some part of this change, *the X91 will not work!* I will try it without the added vendor, though.

**Comment by ewtoombs** [comment]
I don't know why I had to add my controller to this list. I just know that I did. Without at least some part of this change, *the X91 will not work!* I will try it without the added vendor, though.

**Comment by cgutman** [comment]
How are you testing?

**Comment by Oscillope** [comment]
Sorry to ressurrect this PR but I noticed it was still open... I also have an X91. It is recognized as a generic controller using the module built from this git repo (without modification) however the upstream version of the module that came with my kernel doesn't see it.

It looks like the Hyperkin vendor ID was never pushed [upstream](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/input/joystick/xpad.c#n402) even though it was added to this repo in 4515b27 two years ago.

**Comment by paroj** [comment]
fixed in 79113b94344c23b0a85d686eb6305b8bd03ca6d4

**Pull request closed without merging**
