### PR TITLE
Input: xpad - Update xboxone fw2015 init packet

### PR DESCRIPTION
**Pull request by luk1337**
Appending { 0x05, 0x20, 0x02, 0x0f, 0x06 } to
xboxone_fw2015_init fixes an issue where the
controller is somewhat stuck in bluetooth
mode until you plug it into Windows PC.

Signed-off-by: LuK1337 <priv.luk@gmail.com>

### CODE REVIEW

**Comment by luk1337** [comment]
May also fix https://github.com/paroj/xpad/issues/145

**Comment by lordgault** [comment]
> May also fix #145, cc: @lordgault

I don't have Windows installed.
I deleted it completely in a fit.

**Comment by luk1337** [comment]
That's the point, this patch should let you use /glitched/ pad.

**Comment by paroj** [comment]
ok, lets try this

**Pull request merged**
