### PR TITLE
Add deadzone support for analog sticks

### PR DESCRIPTION
**Pull request by ChrisDeadman**

### CODE REVIEW

**Comment by paroj** [comment]
not sure whether this really should be in the kernel driver or rather be handled on a higher level. (SDL2/ X11)

**Comment by cgutman** [comment]
@paroj I agree. I don't think upstream would be willing to take this.

There are many different ways to implement a deadzone (see here: http://www.third-helix.com/2013/04/12/doing-thumbstick-dead-zones-right.html ) and I don't think we should be in the position to choose one for userspace - not to mention changing our DZ algorithm in the future would break userspace.

**Comment by ChrisDeadman** [comment]
I agree that this is implementation is pretty much the "poor man's approach" (thanks for the link btw. @cgutman, good read) and that I should at least change it to be a radial deadzone check.
As for the intention, I added the deadzone support as kind of a last resort if a userspace application does not have any deadzone support at all.

**Comment by paroj** [comment]
Any deadzone implementation is not xpad specific and could be also used by other drivers. Therfore I think this should rather go in the upper levels like SDL.

**Pull request closed without merging**
