### PR TITLE
Hyperkin Duke Variant 1.01

### PR DESCRIPTION
**Pull request by cybik**
A Hyperkin Duke with `idVendor=2e24` and `idProduct=1618` is known to be in the wild. Adding this DeviceID set in `/sys/bus/usb/drivers/xpad/new_id` allows xpad to operate the controller just fine, so this PR should be all xpad needs to operate the pad.

### CODE REVIEW

**Comment by cgutman** [comment]
This change shouldn't be necessary to use the Duke. All that is required is the `XPAD_XBOXONE_VENDOR(0x2e24)` entry in the `xpad_table[]`, which already exists.

`xpad_device[]` just provides friendly names to most of the controllers in the list. Without an entry there, `xpad_probe()` will derive the gamepad type based on the vendor-defined USB interfaces and use a generic name (Generic X-Box pad).

If this change does make an actual difference with controller functionality, that means we have a bug in `xpad_probe()` or something. Can you get a `lsusb -v` for this controller?

**Comment by cybik** [comment]
Unfortunately with the xpad_device block only, the pad doesn't get "recognized" or initialized - for example, it doesn't respond to any input presses and Steam does not detect it even in Generic Pad mode.

It's only with the idProduct added specifically (through new_id) that the pad initializes properly (and shows the little video on the middle screen).

Here's a gist with the Duke's `lsusb -v`: https://gist.github.com/cybik/cbb99c6b153129f17009a7be4780d099

**Comment by cgutman** [comment]
`/sys/bus/usb/drivers/xpad/new_id` does something different than your PR is doing. It is the equivalent of adding a `{ USB_DEVICE(0x2e24, 0x1618) }` entry to `xpad_table[]`, not `xpad_device[]`.

The lsusb output looks correct and it would match the `XPAD_XBOXONE_VENDOR(0x2e24)` entry for sure (Class = 255, Subclass = 71, Protocol = 208).

Are you certain that you're actually using _this_ version of xpad when you're performing your tests, not the upstream xpad? Upstream xpad does not have `XPAD_XBOXONE_VENDOR(0x2e24)` yet, because I need to submit a patch to avoid the controllers resetting themselves when userspace isn't reading from them.

**Comment by cybik** [comment]
Oh. Yeah I'm using mainline/upstream.

The odd thing is the duke hasn't been resetting at all with upstream 'til now.

Is there a PPA I should be pulling from to test the current state of xpad?

**Pull request closed without merging**
