### PR TITLE
XBox One Mad Cats Steering Wheel Patch

### PR DESCRIPTION
**Pull request by hidemune**
Please merge me.

### CODE REVIEW

**Comment by cgutman** [comment]
What is this supposed to do?

**Comment by hidemune** [comment]
This patch add supporting...


      Mad Catz Pro Racing Force Feedback Wheel ＆ Pedals (Xbox One) <https://www.google.co.jp/url?sa=t&rct=j&q=&esrc=s&source=web&cd=6&cad=rja&uact=8&ved=0ahUKEwic5aWWo93TAhWInZQKHXDXAacQFgg4MAU&url=http%3A%2F%2Fmadcatz.co.jp%2Fproducts%2Fmadcatz%2FMCX-RW-MC-PRO%2Fdetail.html&usg=AFQjCNGxWnz6GhrSByHsua6AVGcB_2xC4Q>


Thanks!!!

**Comment by cgutman** [comment]
Can you explain in detail each change that has been made and why they are needed?

All it appears that you've done from a cursory glance (ignoring bugs) is that you're dividing the right stick and triggers by 64. Can you explain why this is needed and if you have any documentation that indicates that this is correct?

**Comment by hidemune** [comment]
Although this wheel was able to take a value with the existing driver, I think that there is a part which is probably deviated by 6 bits. I adjusted by dividing by 64.

**Comment by hidemune** [comment]
I got log just now.

i will check today's night(JST+9).

May  8 08:10:03 user-H81M-S04 kernel: [53474.471385] xpad-dbg: 00000000: 20 00 41 11 00 00 d9 ff 00 00 00 00 00 00 00 00 00 84 03 ff c8 62 6f 78 2e 49 6e 70 75 74 2e 57
May  8 08:10:03 user-H81M-S04 kernel: [53474.471386] xpad-dbg: 00000020: 68 65 65 6c 18 00 57 69 6e 64 6f 77 73 2e 58 62 6f 78 2e 49 6e 70 75 74 2e 57 68 65 65 6c 27 00
May  8 08:10:03 user-H81M-S04 kernel: [53474.475386] xpad-dbg: 00000000: 20 00 42 11 00 00 ff ff 00 00 00 00 00 00 00 00 00 84 03 ff c8 62 6f 78 2e 49 6e 70 75 74 2e 57
May  8 08:10:03 user-H81M-S04 kernel: [53474.475387] xpad-dbg: 00000020: 68 65 65 6c 18 00 57 69 6e 64 6f 77 73 2e 58 62 6f 78 2e 49 6e 70 75 74 2e 57 68 65 65 6c 27 00

**Pull request closed without merging**
